# Generated by Django 4.1.6 on 2023-02-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero_app', '0007_weapon_damage_alter_armorhero_bought_armors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('events', models.IntegerField(choices=[(1, 'One-way tunnel'), (2, 'Cross'), (3, 'End of tunel'), (4, 'Boss')], default=1, null=True)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MazeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.IntegerField(default=1)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero_app.hero')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay_app.maze')),
            ],
        ),
        migrations.AddField(
            model_name='maze',
            name='hero',
            field=models.ManyToManyField(through='gameplay_app.MazeHero', to='hero_app.hero'),
        ),
    ]
