# Generated by Django 4.1.6 on 2023-02-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay_app', '0002_maze_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazehero',
            name='active_position',
            field=models.BooleanField(default=True),
        ),
    ]
