# Generated by Django 4.1.6 on 2023-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='damage_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='damage_reduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='defence_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
