# Generated by Django 4.1.6 on 2023-02-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0002_hero_attack_bonus_hero_damage_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='damage',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage',
            field=models.IntegerField(default=3),
        ),
    ]
