# Generated by Django 4.1.6 on 2023-02-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0004_weapon_initiative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='initiative',
        ),
        migrations.AddField(
            model_name='hero',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
    ]
