# Generated by Django 4.1.6 on 2023-02-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0005_remove_weapon_damage_remove_weapon_initiative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weaponhero',
            name='bought_weapons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons_hero', to='hero_app.weapon'),
        ),
        migrations.AlterField(
            model_name='weaponhero',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons_hero', to='hero_app.hero'),
        ),
    ]
