# Generated by Django 4.1.6 on 2023-02-08 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0006_alter_hero_level_alter_weaponhero_bought_weapons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='damage',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='armorhero',
            name='bought_armors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_hero', to='hero_app.armor'),
        ),
        migrations.AlterField(
            model_name='armorhero',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_hero', to='hero_app.hero'),
        ),
    ]
