# Generated by Django 4.1.6 on 2023-02-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0007_weapon_damage_alter_armorhero_bought_armors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='number_of_attacks',
            field=models.IntegerField(default=1),
        ),
    ]
