# Generated by Django 4.1.6 on 2023-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0008_hero_number_of_attacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='attack_bonus',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='defence_bonus',
        ),
        migrations.AddField(
            model_name='hero',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='charisma_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='dexterity_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='endurance_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='wisdom_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='damage',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='hero',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='endurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='health_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='max_health_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.IntegerField(choices=[(1, 'Human'), (2, 'Dwarf'), (3, 'Elf'), (4, 'Gnome'), (5, 'Half-elf'), (6, 'Half-orc'), (7, 'Halfling')]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
