# Generated by Django 4.1.6 on 2023-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0011_alter_weapon_type_alter_weapon_weapon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='number_of_attacks',
            field=models.IntegerField(default=0),
        ),
    ]
