# Generated by Django 4.1.6 on 2023-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0012_weapon_number_of_attacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='type',
            field=models.IntegerField(choices=[(1, 'Light Armor'), (2, 'Medium Armor'), (3, 'Heavy armor')], default=1),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.IntegerField(choices=[(1, 'Attack without weapon'), (2, 'Light melee weapon'), (3, 'One-handed combat weapon'), (4, 'A two-handed melee weapon')], default=1),
        ),
    ]
