# Generated by Django 4.1.6 on 2023-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.IntegerField(choices=[(1, 'Human'), (2, 'Elf'), (3, 'Dwarf'), (4, 'Orc')]),
        ),
    ]
