# Generated by Django 4.1.6 on 2023-02-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_hero_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('defence_bonus', models.IntegerField()),
                ('attack_bonus', models.IntegerField()),
                ('damage_reduction', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armor')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('defence_bonus', models.IntegerField()),
                ('attack_bonus', models.IntegerField()),
                ('damage_bonus', models.IntegerField()),
                ('price', models.IntegerField()),
                ('hero', models.ManyToManyField(null=True, through='main.HeroEquipment', to='main.hero')),
            ],
        ),
        migrations.AddField(
            model_name='heroequipment',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weapon'),
        ),
        migrations.AddField(
            model_name='armor',
            name='hero',
            field=models.ManyToManyField(null=True, through='main.HeroEquipment', to='main.hero'),
        ),
    ]
