# Generated by Django 4.1.6 on 2023-02-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_armor_hero_remove_weapon_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_weapons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weapon')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hero')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_armors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armor')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hero')),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='hero',
            field=models.ManyToManyField(through='main.ArmorHero', to='main.hero'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='hero',
            field=models.ManyToManyField(through='main.WeaponHero', to='main.hero'),
        ),
    ]
