# Generated by Django 4.1.6 on 2023-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usercurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='diamonds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='diamonds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weaponhero',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='armor',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
