# Generated by Django 4.1.6 on 2023-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_armor_diamonds_weapon_diamonds_weaponhero_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
