# Generated by Django 4.1.6 on 2023-02-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
