# Generated by Django 4.1.6 on 2023-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0002_monster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='damage_reduction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='difficult',
            field=models.IntegerField(null=True),
        ),
    ]
