# Generated by Django 4.1.6 on 2023-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0004_remove_monster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='damage',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='monster',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
    ]
