# Generated by Django 4.1.6 on 2023-02-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0006_alter_monster_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='defence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dice',
            field=models.IntegerField(choices=[(1, 3), (2, 4), (3, 6), (4, 8), (5, 10), (6, 12), (7, 20)]),
        ),
    ]
