# Generated by Django 4.1.6 on 2023-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0007_monster_attack_bonus_monster_damage_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='health_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='max_health_points',
            field=models.IntegerField(default=0),
        ),
    ]
