# Generated by Django 4.1.6 on 2023-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0008_alter_monster_health_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='slug',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
