# Generated by Django 4.1.6 on 2023-02-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0009_monster_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='dice',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='level',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='number_of_dices',
        ),
        migrations.AddField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='charisma_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='endurance_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='experience',
            field=models.IntegerField(choices=[(1, 5400), (2, 3600), (3, 2700), (4, 1800), (5, 1350), (6, 900), (7, 600), (8, 300)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='number_of_attacks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='wisdom_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
